import Head from "next/head";
import styles from "@/styles/About.module.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] }); 

export default function about() {
    return (
        <>
         <Head>
        <title>Hackers' Chronicle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}  ${inter.className}`}>
        <div className={styles.container}>
            <h1>This is about page</h1>
        </div>
        
      </main>  
        </>
    );
}