import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Dummy from "./dumy";


// If your want to add any global css you have to add it in _app file 
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hackers' Chronicle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <main className={`${styles.main} ${inter.className}`}>
      
       <div className={styles.container}>
        <h1 >Hackers' Chronicle</h1> 
       </div>
      <div className={styles.blogsContainer}>
        <h2 className={styles.blogItem}>Popular blogs</h2>
        <div className={styles.blogItem}>
          <h3>How to learn javascript in 2024?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, sed. Tempore voluptates obcaecati quod labore asperiores aliquam, doloremque exercitationem quisquam omnis quia quae ea maiores.........</p>
        </div>
        <div className={styles.blogItem}>
          <h3>How to learn javascript in 2024?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, sed. Tempore voluptates obcaecati quod labore asperiores aliquam, doloremque exercitationem quisquam omnis quia quae ea maiores.........</p>
        </div>
        <div className={styles.blogItem}>
          <h3>How to learn javascript in 2024?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, sed. Tempore voluptates obcaecati quod labore asperiores aliquam, doloremque exercitationem quisquam omnis quia quae ea maiores.........</p>
        </div>
        <div className={styles.blogItem}>
          <h3>How to learn javascript in 2024?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, sed. Tempore voluptates obcaecati quod labore asperiores aliquam, doloremque exercitationem quisquam omnis quia quae ea maiores.........</p>
        </div>
        <div className={styles.blogItem}>
          <h3>How to learn javascript in 2024?</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos, sed. Tempore voluptates obcaecati quod labore asperiores aliquam, doloremque exercitationem quisquam omnis quia quae ea maiores.........</p>
        </div>
       
        
      </div>
      </main>
    </>
  );
}
